//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizBulb.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizBulb.Localization.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Device Manually.
        /// </summary>
        internal static string AddDeviceManually {
            get {
                return ResourceManager.GetString("AddDeviceManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Device.
        /// </summary>
        internal static string AddNewDevice {
            get {
                return ResourceManager.GetString("AddNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your changes before exiting?.
        /// </summary>
        internal static string AskSaveExit {
            get {
                return ResourceManager.GetString("AskSaveExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulb.
        /// </summary>
        internal static string Bulb {
            get {
                return ResourceManager.GetString("Bulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulb Description.
        /// </summary>
        internal static string BulbDescription {
            get {
                return ResourceManager.GetString("BulbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulbs.
        /// </summary>
        internal static string Bulbs {
            get {
                return ResourceManager.GetString("Bulbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulb Type.
        /// </summary>
        internal static string BulbType {
            get {
                return ResourceManager.GetString("BulbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        internal static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Folder.
        /// </summary>
        internal static string ChooseFolder {
            get {
                return ResourceManager.GetString("ChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Program.
        /// </summary>
        internal static string CloseProgramTitle {
            get {
                return ResourceManager.GetString("CloseProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Color.
        /// </summary>
        internal static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Device.
        /// </summary>
        internal static string DeleteDevice {
            get {
                return ResourceManager.GetString("DeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Light Mode.
        /// </summary>
        internal static string DeleteLightMode {
            get {
                return ResourceManager.GetString("DeleteLightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Room.
        /// </summary>
        internal static string DeleteRoom {
            get {
                return ResourceManager.GetString("DeleteRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Scene.
        /// </summary>
        internal static string DeleteScene {
            get {
                return ResourceManager.GetString("DeleteScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Config.
        /// </summary>
        internal static string DriverConfig {
            get {
                return ResourceManager.GetString("DriverConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Modes.
        /// </summary>
        internal static string DynamicModes {
            get {
                return ResourceManager.GetString("DynamicModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not appear to be connected to the internet..
        /// </summary>
        internal static string ErrorNoInternet {
            get {
                return ResourceManager.GetString("ErrorNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a number..
        /// </summary>
        internal static string ErrorValueNotNumber {
            get {
                return ResourceManager.GetString("ErrorValueNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range..
        /// </summary>
        internal static string ErrorValueOutOfRange {
            get {
                return ResourceManager.GetString("ErrorValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EwfHex.
        /// </summary>
        internal static string EwfHex {
            get {
                return ResourceManager.GetString("EwfHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version.
        /// </summary>
        internal static string FirmwareVersion {
            get {
                return ResourceManager.GetString("FirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting bulb info for &apos;{0}&apos; ....
        /// </summary>
        internal static string GettingBulbInfoForX {
            get {
                return ResourceManager.GetString("GettingBulbInfoForX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Access.
        /// </summary>
        internal static string HasInternet {
            get {
                return ResourceManager.GetString("HasInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home ID.
        /// </summary>
        internal static string HomeId {
            get {
                return ResourceManager.GetString("HomeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Name.
        /// </summary>
        internal static string HomeName {
            get {
                return ResourceManager.GetString("HomeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homes.
        /// </summary>
        internal static string Homes {
            get {
                return ResourceManager.GetString("Homes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Powered Off.
        /// </summary>
        internal static string IsPoweredOff {
            get {
                return ResourceManager.GetString("IsPoweredOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Powered On.
        /// </summary>
        internal static string IsPoweredOn {
            get {
                return ResourceManager.GetString("IsPoweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light is off..
        /// </summary>
        internal static string LightIsOff {
            get {
                return ResourceManager.GetString("LightIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light is on..
        /// </summary>
        internal static string LightIsOn {
            get {
                return ResourceManager.GetString("LightIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        internal static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Modes.
        /// </summary>
        internal static string LightModes {
            get {
                return ResourceManager.GetString("LightModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Off.
        /// </summary>
        internal static string LightOff {
            get {
                return ResourceManager.GetString("LightOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light On.
        /// </summary>
        internal static string LightOn {
            get {
                return ResourceManager.GetString("LightOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Settings.
        /// </summary>
        internal static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address.
        /// </summary>
        internal static string MACAddress {
            get {
                return ResourceManager.GetString("MACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Color.
        /// </summary>
        internal static string NamedColor {
            get {
                return ResourceManager.GetString("NamedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Colors.
        /// </summary>
        internal static string NamedColors {
            get {
                return ResourceManager.GetString("NamedColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Name.
        /// </summary>
        internal static string NetworkName {
            get {
                return ResourceManager.GetString("NetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Light Mode.
        /// </summary>
        internal static string NewLightMode {
            get {
                return ResourceManager.GetString("NewLightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Room.
        /// </summary>
        internal static string NewRoom {
            get {
                return ResourceManager.GetString("NewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scene.
        /// </summary>
        internal static string NewScene {
            get {
                return ResourceManager.GetString("NewScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Access.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection Not Determined.
        /// </summary>
        internal static string NotDetermined {
            get {
                return ResourceManager.GetString("NotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Bulb.
        /// </summary>
        internal static string PingBulb {
            get {
                return ResourceManager.GetString("PingBulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered Off.
        /// </summary>
        internal static string PoweredOff {
            get {
                return ResourceManager.GetString("PoweredOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered On.
        /// </summary>
        internal static string PoweredOn {
            get {
                return ResourceManager.GetString("PoweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Off.
        /// </summary>
        internal static string PowerOff {
            get {
                return ResourceManager.GetString("PowerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On.
        /// </summary>
        internal static string PowerOn {
            get {
                return ResourceManager.GetString("PowerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Status.
        /// </summary>
        internal static string PowerStatus {
            get {
                return ResourceManager.GetString("PowerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined.
        /// </summary>
        internal static string Predefined {
            get {
                return ResourceManager.GetString("Predefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity.
        /// </summary>
        internal static string Proximity {
            get {
                return ResourceManager.GetString("Proximity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh All.
        /// </summary>
        internal static string RefreshAll {
            get {
                return ResourceManager.GetString("RefreshAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying {0} ....
        /// </summary>
        internal static string RetryingX {
            get {
                return ResourceManager.GetString("RetryingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room ID.
        /// </summary>
        internal static string RoomId {
            get {
                return ResourceManager.GetString("RoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Name.
        /// </summary>
        internal static string RoomName {
            get {
                return ResourceManager.GetString("RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        internal static string SaveAsEllipses {
            get {
                return ResourceManager.GetString("SaveAsEllipses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string SaveChangesTitle {
            get {
                return ResourceManager.GetString("SaveChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveSettings.
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Complete.
        /// </summary>
        internal static string ScanComplete {
            get {
                return ResourceManager.GetString("ScanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan For Bulbs.
        /// </summary>
        internal static string ScanForBulbs {
            get {
                return ResourceManager.GetString("ScanForBulbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for bulbs....
        /// </summary>
        internal static string ScanningBulbs {
            get {
                return ResourceManager.GetString("ScanningBulbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for bulbs... ({0} bulbs discovered).
        /// </summary>
        internal static string ScanningBulbsXBulbsFound {
            get {
                return ResourceManager.GetString("ScanningBulbsXBulbsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Now.
        /// </summary>
        internal static string ScanNow {
            get {
                return ResourceManager.GetString("ScanNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        internal static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene ID.
        /// </summary>
        internal static string SceneId {
            get {
                return ResourceManager.GetString("SceneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene Name.
        /// </summary>
        internal static string SceneName {
            get {
                return ResourceManager.GetString("SceneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenes.
        /// </summary>
        internal static string Scenes {
            get {
                return ResourceManager.GetString("Scenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Light Mode.
        /// </summary>
        internal static string SelectMode {
            get {
                return ResourceManager.GetString("SelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Network.
        /// </summary>
        internal static string SelectNetwork {
            get {
                return ResourceManager.GetString("SelectNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Room.
        /// </summary>
        internal static string SelectRoom {
            get {
                return ResourceManager.GetString("SelectRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Scene.
        /// </summary>
        internal static string SelectScene {
            get {
                return ResourceManager.GetString("SelectScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Color.
        /// </summary>
        internal static string SetColor {
            get {
                return ResourceManager.GetString("SetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Light Mode.
        /// </summary>
        internal static string SetLightMode {
            get {
                return ResourceManager.GetString("SetLightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Timeout.
        /// </summary>
        internal static string SetTimeout {
            get {
                return ResourceManager.GetString("SetTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Strength.
        /// </summary>
        internal static string SignalStrength {
            get {
                return ResourceManager.GetString("SignalStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Modes.
        /// </summary>
        internal static string StandardModes {
            get {
                return ResourceManager.GetString("StandardModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Scanning.
        /// </summary>
        internal static string StopScanning {
            get {
                return ResourceManager.GetString("StopScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (in seconds).
        /// </summary>
        internal static string TimeoutSeconds {
            get {
                return ResourceManager.GetString("TimeoutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined.
        /// </summary>
        internal static string UserDefined {
            get {
                return ResourceManager.GetString("UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined Light Mode.
        /// </summary>
        internal static string UserDefinedLightMode {
            get {
                return ResourceManager.GetString("UserDefinedLightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number between {0} and {1}.
        /// </summary>
        internal static string WarnEnterNumberRange {
            get {
                return ResourceManager.GetString("WarnEnterNumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a network adapter to continue..
        /// </summary>
        internal static string WarnSelectAdapter {
            get {
                return ResourceManager.GetString("WarnSelectAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WizBulb.
        /// </summary>
        internal static string WizBulb {
            get {
                return ResourceManager.GetString("WizBulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Bulbs.
        /// </summary>
        internal static string XBulbs {
            get {
                return ResourceManager.GetString("XBulbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Bulbs Discovered.
        /// </summary>
        internal static string XBulbsFound {
            get {
                return ResourceManager.GetString("XBulbsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} db.
        /// </summary>
        internal static string Xdb {
            get {
                return ResourceManager.GetString("Xdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
